live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font Mono"
style = "Meduim"

[font.bold_italic]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[46;5u"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[59;5u"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[window]
blur = false
decorations = "buttonless"
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Terminal"

[colors.primary] # Normal colors
# Bright colors
background = '0x24283b'
foreground = '0xc0caf5'

[colors.normal]
black = '0x1d202f'
red = '0xf7768e'
green = '0x9ece6a'
yellow = '0xe0af68'
blue = '0x7aa2f7'
magenta = '0xbb9af7'
cyan = '0x7dcfff'
white = '0xa9b1d6'

[colors.bright]
black = '0x414868'
red = '0xf7768e'
green = '0x9ece6a'
yellow = '0xe0af68'
blue = '0x7aa2f7'
magenta = '0xbb9af7'
cyan = '0x7dcfff'
white = '0xc0caf5'

[[colors.indexed_colors]]
index =16
color = '0xff9e64'

[[colors.indexed_colors]]
index =17
color = '0xdb4b4b'

[cursor.style]
blinking = "Never"

[window.padding]
x = 10
y = 15
